### ISSUE TITLE
Add License?

### ISSUE THREAD

**Issue by kingcharlezz** [jxnl/video-summary-streamer#2]
I wanted to bring up a small but important aspect that seems to be missing in the repository - a license. I understand that this might not be at the top of your priorities, but adding a license can clarify the rules around the use of your project's code and potentially encourage wider participation.

If you're open to it, I suggest a permissive license like the MIT License. This allows commercial use while providing protections for the project contributors.

Thank you for considering this proposal. I really appreciate you making this project and I'm excited to see how it continues to evolve.

**Comment by jxnl** [comment]
super busy these days, if you make a pr you i'll merge it!

**Comment by jxnl** [comment]
TY!
